### ISSUE TITLE
Support servant-0.13

### ISSUE THREAD

**Issue by imalsogreg** [haskell-servant/servant-snap#18]
Specifically, the new streaming combinators.

**Comment by antislava** [comment]
Made small changes to adapt to the new ToStreamGenerator (https://github.com/antislava/servant-snap/commit/3f899473a12890777caa226ab249498ab5442837) but didn't manage to fix the streaming component in greet.hs example. I am new to both servant and snap. (Otherwise, servant-snap with above changes does compile with e.g. the latest reflex-platform/obelisk, with tests and example disabled)

example/greet.hs:86:10: error:
• Couldn't match type ‘Servant.Server.Internal.ServerT (Stream 'GET 200 NetstringFraming JSON (StreamGenerator Greet)) '[] (Handler App App)’
with
‘m0 (StreamGenerator Greet)’

**Comment by hvr** [comment]
@imalsogreg btw, didn't http://hackage.haskell.org/package/servant-snap-0.8.2 add support for servant-0.13 ?

**Comment by antislava** [comment]
@hvr It does work with servant-0.13 actually
Here, with explicit dependency overrides https://github.com/antislava/servant-snap/tree/antislava/servant_13:
```
nix-shell ./release.nix --argstr compiler ghc844 --arg haskell-overrides ./haskell-overrides_servant_13.nix -A servant-snap-ex-no-check.env
cabal new-build --flag examples :snap-greet
```
I should probably open a separate issue about servant-0.14+ compatibility (caused by a change in the ToStreamGenerator type signature apparently).

**Comment by imalsogreg** [comment]
Thanks for bringing this up. Yes, I'll close this ticket, and if you could open another for 0.14, @antislava , it's much appreciated!
